version: "3.9"

services:
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server --binding 0.0.0.0"
    container_name: rails
    ports:
      - 3000:3000
    volumes:
      - .:/app

  webpack:
    build: .
    command: bash -c "rm -rf public/packs && bin/webpack-dev-server"
    container_name: webpack
    ports:
      - 3035:3035
    volumes:
      - .:/app
